main:
  - name: Home
    pageRef: /
    weight: 10
  - name: About
    pageRef: /about
    weight: 20
  - name: Contact
    pageRef: /contact
    weight: 30
  - name: Newsletter
    url: https://newsletter.digibloom.net
    weight: 40
    params:
      external: true
